const express = require('express');
const router = express.Router();
const customerController =require('../controllers/customer.controller');

router.get('/',customerController.getAllCustomer);
router.get('/profile/:id',customerController.getCustomerProfile);
router.put('/update/profile/:id',customerController.updateCustomerProfile);
router.get('/statusRegisterService',customerController.getStatusRegisterService);
router.get('/statusRegisterServiceById/:id',customerController.getStatusRegisterServiceById);
router.get('/registerService/:id',customerController.getRegisterServiceById);
router.get('/registerServiceByCustomer/:id',customerController.getRegisterServiceByCustomer);
router.post('/create/registerService',customerController.addRegisterService);
router.post('/create/feedbackByCustomer',customerController.addFeedBackByCustomer);
router.post('/delete/feedback/:id',customerController.deleteFeedback);
router.put('/update/feedback/:id',customerController.updateFeedback);
router.post('/create/feedbackdetailbycustomer',customerController.addFeedBackDetailByCustomer);
router.delete('/delete/feedbackdetail/:id',customerController.deleteFeedbackDetailByFeedbackDetailId);
router.put('/update/feedbackDetail/:id',customerController.updateFeedbackDetail);
router.get('/getFeedbackOfSalon/:id',customerController.getFeedbackOfSalon);
router.get('/getFeedbackDetail/:feedBackId',customerController.getFeedbackDetail);
module.exports = router;