const express = require('express');
const cors =require('cors');
const router = express.Router();
const salonOwnerController = require('../controllers/salonOwner.controller');
const imageSalonController = require('../controllers/imageSalon.controller');
const serviceController = require('../controllers/service.controller');
const categoryServiceController = require('../controllers/categoryService.controller');
const imageServiceController = require('../controllers/imageSerice.controller');
const feedbackController = require('../controllers/feedback.controller');
const feedbackDetailController = require('../controllers/feedbacDetail.controller');
const staffController = require('../controllers/staff.controller');
const { param,body, validationResult } = require('express-validator');
const {check} = require('express-validator');
const validate = require('../common/valiator');
const auth = require('../middleware/auth');

router.get('/',cors(),salonOwnerController.salonOwner);
router.get('/profile/:id',cors(),auth,salonOwnerController.getSalonOwnerProfile);
router.put('/update/profile/:id',cors(),salonOwnerController.updateSalonOwnerProfile);
router.get('/imageSalon/:idSalon',cors(),imageSalonController.getImageSalon);
router.post('/create/imageToImageSalon',cors(),imageSalonController.addImageToImageSalon);
router.delete('/delete/imageOfImageSalon/:id',cors(),imageSalonController.deleteImageOfImageSalon);
router.post('/create/service',cors(),serviceController.addServiceSalon);
router.delete('/delete/service/:idService',cors(),serviceController.deleteServiceSalon);
router.get('/Service/:idSalon',cors(),serviceController.getServiceOfSalon);
router.put('/update/Service/:idService',cors(),serviceController.updateServiceSalon);
router.post('/create/categoryService',cors(),categoryServiceController.addCategoryService);
router.get('/get/categoryService/:idService',cors(),categoryServiceController.getCategoryServiceOfService);
router.delete('/delete/categoryService/:id',cors(),categoryServiceController.deleteCategoryService);
router.post('/create/imageService',cors(),imageServiceController.addImageService);
router.get('/imageService/:id',cors(),imageServiceController.getImageService);
router.delete('/delete/imageService/:id',cors(),imageServiceController.deleteImageService);
router.post('/createFeedBackBySalon',cors(),feedbackController.addFeedBackBySalon);
router.get('/getFeedbackOfSalon/:id',cors(),feedbackController.getFeedbackOfSalon);
router.delete('/delete/feedback/:id',cors(),feedbackController.deleteFeedback);
router.put('/update/feedback/:id',cors(),feedbackController.updateFeedback);
router.post('/create/feedBackDetailBySalon',cors(),feedbackDetailController.addFeedBackDetailBySalon);
router.get('/getFeedbackDetail/:feedBackId',cors(),feedbackDetailController.getFeedbackDetail);
router.delete('/delete/feedbackdetail/:id',cors(),feedbackDetailController.deleteFeedbackDetailByFeedbackDetailId);
router.put('/update/feedbackdetail/:id',cors(),feedbackDetailController.updateFeedbackDetail);
router.get('/staff/:id',cors(),staffController.getStaff);
router.post('/create/staff',cors(),staffController.addStaff);
router.put('/update/staff/:id',cors(),staffController.updateStaff);
router.delete('/delete/staff/:id',cors(),staffController.deleteStaff);
module.exports = router;